version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - govet
    - unused
    - misspell
    - nolintlint
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
