codecov:
  require_ci_to_pass: false
  branch: main

coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
